name: Build and Deploy to Google Play

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Unity
      uses: game-ci/setup-unity@v1
      with:
        unity-version: 2021.3.13f1

    - name: Build Unity project for Android
      run: |
        mkdir -p Build/Android
        unity-editor \
          -batchmode \
          -nographics \
          -silent-crashes \
          -quit \
          -logFile \
          -projectPath . \
          -executeMethod BuildCommand.PerformBuild \
          -buildTarget android \
          -customBuildTargetName "android" \
          -customBuildName "CV_Idle" \
          -customBuildPath "Build/Android/CV_Idle.aab" \
          -androidVersionCode 20

    - name: Find .aab file after build
      id: find_aab
      run: |
        AAB_PATH=$(find ./Build/Android -name "*.aab")
        echo "AAB_PATH=$AAB_PATH" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AndroidAppBundle
        path: ${{ env.AAB_PATH }}
        if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: AndroidAppBundle
        path: build/Android

    - name: Deploy to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: ${{ secrets.GOOGLE_PLAY_API_JSON }}
        packageName: com.DefaultCompany.com.unity.template.mobile2D
        releaseFiles: build/Android/*.aab
        track: internal
